name: RandomChest
main: me.kapehh.main.RandomChest.Main
author: kapehh
version: 1.0.0
commands:
    randomchest:
        usage: /<command> [open <chestname> [playername] | reload]
        description: RandomChest